[package]
name = "singleton-task"
version = "0.1.0"
edition = "2024"
authors = ["周睿 <zrufo747@outlook.com>"]
description = "A singleton task based on tokio"

[dependencies]
futures = "0.3"
log = "0.4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
env_logger = "0.11"
