[package]
name = "singleton-task"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
log = "0.4"


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"